USE [master]
GO

/****** Object:  Database [DBAirlineReservation]    Script Date: 19-11-2021 22:43:55 ******/
CREATE DATABASE [DBAirlineReservation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBAirlineReservation', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DBAirlineReservation.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBAirlineReservation_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DBAirlineReservation_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBAirlineReservation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBAirlineReservation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DBAirlineReservation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBAirlineReservation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBAirlineReservation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DBAirlineReservation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBAirlineReservation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBAirlineReservation] SET  MULTI_USER 
GO

ALTER DATABASE [DBAirlineReservation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBAirlineReservation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBAirlineReservation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBAirlineReservation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBAirlineReservation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBAirlineReservation] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DBAirlineReservation] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DBAirlineReservation] SET  READ_WRITE 
GO

